# Generated by Django 3.0.8 on 2020-08-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tujuan',
            name='img',
        ),
        migrations.RemoveField(
            model_name='tujuan',
            name='specof',
        ),
    ]
