# Generated by Django 3.0.8 on 2020-08-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20200808_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='tujuan',
            name='img',
            field=models.ImageField(default='', upload_to='pics'),
            preserve_default=False,
        ),
    ]
